aws:
  region: "us-east-1"
  bucket: "your-s3-bucket-name"
  keyPrefix: "path/to/your/key"
gcs:
  bucketName: "your-gcs-bucket-name"
  keyPrefix: "path/to/your/key"
postgres:
  host: "localhost"
  port: 5432
  user: "your-username"
  password: "your-password"
  dbname: "your-dbname"
memcached:
  server: "localhost:11211"
